// @flow
import type {
  ADD_COLUMN_TYPE,
  ADD_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_BOOKMARK_TYPE,
  FETCH_BOOKMARK_SUCCESS_TYPE,
  FETCH_BOOKMARK_FAILRE_TYPE,
  FETCH_NEXT_BOOKMARK_TYPE,
  FETCH_NEXT_BOOKMARK_SUCCESS_TYPE,
  FETCH_NEXT_BOOKMARK_FAILRE_TYPE,
} from './actionTypes.js'

export const ADD_COLUMN: ADD_COLUMN_TYPE = 'ColumnBookmark/ADD_COLUMN'
export const ADD_COLUMN_SUCCESS: ADD_COLUMN_SUCCESS_TYPE =
  'ColumnBookmark/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnBookmark/SET_NEXT_URL'
export const FETCH_BOOKMARK: FETCH_BOOKMARK_TYPE =
  'ColumnBookmark/FETCH_BOOKMARK'
export const FETCH_BOOKMARK_SUCCESS: FETCH_BOOKMARK_SUCCESS_TYPE =
  'ColumnBookmark/FETCH_BOOKMARK_SUCCESS'
export const FETCH_BOOKMARK_FAILRE: FETCH_BOOKMARK_FAILRE_TYPE =
  'ColumnBookmark/FETCH_BOOKMARK_FAILRE'
export const FETCH_NEXT_BOOKMARK: FETCH_NEXT_BOOKMARK_TYPE =
  'ColumnBookmark/FETCH_NEXT_BOOKMARK'
export const FETCH_NEXT_BOOKMARK_SUCCESS: FETCH_NEXT_BOOKMARK_SUCCESS_TYPE =
  'ColumnBookmark/FETCH_NEXT_BOOKMARK_SUCCESS'
export const FETCH_NEXT_BOOKMARK_FAILRE: FETCH_NEXT_BOOKMARK_FAILRE_TYPE =
  'ColumnBookmark/FETCH_NEXT_BOOKMARK_FAILRE'
