// @flow
import type {
  ADD_COLUMN_TYPE,
  ADD_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_TYPE,
  FETCH_SUCCESS_TYPE,
  FETCH_FAILRE_TYPE,
  REMOVE_ITEM_TYPE,
  FETCH_NEXT_TYPE,
  FETCH_NEXT_SUCCESS_TYPE,
  FETCH_NEXT_FAILRE_TYPE,
} from './actionTypes'

export const ADD_COLUMN: ADD_COLUMN_TYPE = 'ColumnBookmark/ADD_COLUMN'
export const ADD_COLUMN_SUCCESS: ADD_COLUMN_SUCCESS_TYPE =
  'ColumnBookmark/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnBookmark/SET_NEXT_URL'
export const FETCH: FETCH_TYPE = 'ColumnBookmark/FETCH'
export const FETCH_SUCCESS: FETCH_SUCCESS_TYPE = 'ColumnBookmark/FETCH_SUCCESS'
export const FETCH_FAILRE: FETCH_FAILRE_TYPE = 'ColumnBookmark/FETCH_FAILRE'
export const REMOVE_ITEM: REMOVE_ITEM_TYPE = 'ColumnBookmark/REMOVE_ITEM'
export const FETCH_NEXT: FETCH_NEXT_TYPE = 'ColumnBookmark/FETCH_NEXT'
export const FETCH_NEXT_SUCCESS: FETCH_NEXT_SUCCESS_TYPE =
  'ColumnBookmark/FETCH_NEXT_SUCCESS'
export const FETCH_NEXT_FAILRE: FETCH_NEXT_FAILRE_TYPE =
  'ColumnBookmark/FETCH_NEXT_FAILRE'
