version: 0.4.{build}

platform:
  - x64

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm install
  - npm install electron-builder@next # force install next version to test electron-builder

test_script:
  - npm run test

build_script:
  - npm run release

skip_non_tags: true
