// @flow
import type {
  ADD_COLUMN_TYPE,
  ADD_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_TYPE,
  FETCH_SUCCESS_TYPE,
  FETCH_FAILRE_TYPE,
  FETCH_NEXT_TYPE,
  FETCH_NEXT_SUCCESS_TYPE,
  FETCH_NEXT_FAILRE_TYPE,
  FETCH_NEW_TYPE,
  FETCH_NEW_SUCCESS_TYPE,
  FETCH_NEW_FAILRE_TYPE,
} from './actionTypes.js'

export const ADD_COLUMN: ADD_COLUMN_TYPE = 'ColumnFollow/ADD_COLUMN'
export const ADD_COLUMN_SUCCESS: ADD_COLUMN_SUCCESS_TYPE =
  'ColumnFollow/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnFollow/SET_NEXT_URL'
export const FETCH: FETCH_TYPE = 'ColumnFollow/FETCH'
export const FETCH_SUCCESS: FETCH_SUCCESS_TYPE = 'ColumnFollow/FETCH_SUCCESS'
export const FETCH_FAILRE: FETCH_FAILRE_TYPE = 'ColumnFollow/FETCH_FAILRE'
export const FETCH_NEXT: FETCH_NEXT_TYPE = 'ColumnFollow/FETCH_NEXT'
export const FETCH_NEXT_SUCCESS: FETCH_NEXT_SUCCESS_TYPE =
  'ColumnFollow/FETCH_NEXT_SUCCESS'
export const FETCH_NEXT_FAILRE: FETCH_NEXT_FAILRE_TYPE =
  'ColumnFollow/FETCH_NEXT_FAILRE'
export const FETCH_NEW: FETCH_NEW_TYPE = 'ColumnFollow/FETCH_USER_NEW_ILLUST'
export const FETCH_NEW_SUCCESS: FETCH_NEW_SUCCESS_TYPE =
  'ColumnFollow/FETCH_NEW_SUCCESS'
export const FETCH_NEW_FAILRE: FETCH_NEW_FAILRE_TYPE =
  'ColumnFollow/FETCH_NEW_FAILRE'
