// flow-typed signature: 154d1f41476328e2bc41a68c8fbc92d5
// flow-typed version: <<STUB>>/autolinker_v^1.4.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autolinker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'autolinker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autolinker/dist/Autolinker' {
  declare module.exports: any;
}

declare module 'autolinker/dist/Autolinker.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autolinker/dist/Autolinker.js' {
  declare module.exports: $Exports<'autolinker/dist/Autolinker'>;
}
declare module 'autolinker/dist/Autolinker.min.js' {
  declare module.exports: $Exports<'autolinker/dist/Autolinker.min'>;
}
