// flow-typed signature: c5d48dbfe00f67d36fad6589f1d46498
// flow-typed version: <<STUB>>/babel-plugin-react-intl-auto_v^0.4.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-intl-auto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-intl-auto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-intl-auto/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-intl-auto/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl-auto/lib/index'>;
}
