// flow-typed signature: e39de04d1ebaa2358f77edf49f26d811
// flow-typed version: <<STUB>>/camelcase-keys_v^4.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camelcase-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'camelcase-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'camelcase-keys/index' {
  declare module.exports: $Exports<'camelcase-keys'>;
}
declare module 'camelcase-keys/index.js' {
  declare module.exports: $Exports<'camelcase-keys'>;
}
