// flow-typed signature: 16c4cbaa7c5d46252c2d3eb707419498
// flow-typed version: <<STUB>>/electron-dl_v^1.6.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-dl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-dl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-dl/index' {
  declare module.exports: $Exports<'electron-dl'>;
}
declare module 'electron-dl/index.js' {
  declare module.exports: $Exports<'electron-dl'>;
}
