// flow-typed signature: eda9b09eb1304c57a509ba053ddd2b3a
// flow-typed version: <<STUB>>/electron-referer_v^0.3.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-referer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-referer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-referer/index' {
  declare module.exports: $Exports<'electron-referer'>;
}
declare module 'electron-referer/index.js' {
  declare module.exports: $Exports<'electron-referer'>;
}
