// flow-typed signature: 0059aec19a2b51a1fab2e1adeb9291c4
// flow-typed version: <<STUB>>/eslint-config-xo-react_v^0.10.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-xo-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-xo-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-xo-react/space' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-xo-react/index' {
  declare module.exports: $Exports<'eslint-config-xo-react'>;
}
declare module 'eslint-config-xo-react/index.js' {
  declare module.exports: $Exports<'eslint-config-xo-react'>;
}
declare module 'eslint-config-xo-react/space.js' {
  declare module.exports: $Exports<'eslint-config-xo-react/space'>;
}
