// flow-typed signature: f6b0e4dfd3b532d04516aa9282745075
// flow-typed version: <<STUB>>/eslint-config-xo_v^0.17.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-xo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-xo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-xo/browser' {
  declare module.exports: any;
}

declare module 'eslint-config-xo/esnext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-xo/browser.js' {
  declare module.exports: $Exports<'eslint-config-xo/browser'>;
}
declare module 'eslint-config-xo/esnext.js' {
  declare module.exports: $Exports<'eslint-config-xo/esnext'>;
}
declare module 'eslint-config-xo/index' {
  declare module.exports: $Exports<'eslint-config-xo'>;
}
declare module 'eslint-config-xo/index.js' {
  declare module.exports: $Exports<'eslint-config-xo'>;
}
