// flow-typed signature: a9b00c8a554db61bf5dc96aa548398f6
// flow-typed version: <<STUB>>/hard-rejection_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hard-rejection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hard-rejection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hard-rejection/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hard-rejection/index' {
  declare module.exports: $Exports<'hard-rejection'>;
}
declare module 'hard-rejection/index.js' {
  declare module.exports: $Exports<'hard-rejection'>;
}
declare module 'hard-rejection/register.js' {
  declare module.exports: $Exports<'hard-rejection/register'>;
}
