// flow-typed signature: e8eec91530eee240c83a43b4bb37f754
// flow-typed version: <<STUB>>/lodash.unionby_v^4.8.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.unionby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.unionby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.unionby/index' {
  declare module.exports: $Exports<'lodash.unionby'>;
}
declare module 'lodash.unionby/index.js' {
  declare module.exports: $Exports<'lodash.unionby'>;
}
