// flow-typed signature: b17eb35030b81af0d41cfc6e77f4f9aa
// flow-typed version: <<STUB>>/pixiv-app-api_v^0.10.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixiv-app-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixiv-app-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixiv-app-api/index.flow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixiv-app-api/index.flow.js' {
  declare module.exports: $Exports<'pixiv-app-api/index.flow'>;
}
declare module 'pixiv-app-api/index' {
  declare module.exports: $Exports<'pixiv-app-api'>;
}
declare module 'pixiv-app-api/index.js' {
  declare module.exports: $Exports<'pixiv-app-api'>;
}
