// flow-typed signature: 9f6f854cb20ba08508de7a6d34ef741e
// flow-typed version: <<STUB>>/react-tap-event-plugin_v^2.0.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tap-event-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tap-event-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tap-event-plugin/src/defaultClickRejectionStrategy' {
  declare module.exports: any;
}

declare module 'react-tap-event-plugin/src/injectTapEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tap-event-plugin/src/TapEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tap-event-plugin/src/TouchEventUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tap-event-plugin/src/defaultClickRejectionStrategy.js' {
  declare module.exports: $Exports<'react-tap-event-plugin/src/defaultClickRejectionStrategy'>;
}
declare module 'react-tap-event-plugin/src/injectTapEventPlugin.js' {
  declare module.exports: $Exports<'react-tap-event-plugin/src/injectTapEventPlugin'>;
}
declare module 'react-tap-event-plugin/src/TapEventPlugin.js' {
  declare module.exports: $Exports<'react-tap-event-plugin/src/TapEventPlugin'>;
}
declare module 'react-tap-event-plugin/src/TouchEventUtils.js' {
  declare module.exports: $Exports<'react-tap-event-plugin/src/TouchEventUtils'>;
}
