// flow-typed signature: 4c6f6271a8c07dc8220c4a4a66cf06dc
// flow-typed version: <<STUB>>/react-sortable-pane_v^0.5.4/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sortable-pane'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sortable-pane' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sortable-pane/lib/index' {
  declare module.exports: any;
}

declare module 'react-sortable-pane/lib/pane' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sortable-pane/lib/index.js' {
  declare module.exports: $Exports<'react-sortable-pane/lib/index'>;
}
declare module 'react-sortable-pane/lib/pane.js' {
  declare module.exports: $Exports<'react-sortable-pane/lib/pane'>;
}
