// flow-typed signature: 82ae4c8efad1283e92caef907ae9962b
// flow-typed version: <<STUB>>/residual-scroll-top_v^0.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'residual-scroll-top'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'residual-scroll-top' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'residual-scroll-top/index' {
  declare module.exports: $Exports<'residual-scroll-top'>;
}
declare module 'residual-scroll-top/index.js' {
  declare module.exports: $Exports<'residual-scroll-top'>;
}
