// flow-typed signature: b19fcce1509e7e7412d7ad85eef9ec0b
// flow-typed version: <<STUB>>/stylelint-processor-styled-components_v^0.0.4/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-processor-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-processor-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-processor-styled-components/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/lib/index' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/lib/utils/general' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/lib/utils/parse' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/lib/utils/styled' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/lib/utils/tagged-template-literal' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/src/index' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/src/utils/general' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/src/utils/parse' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/src/utils/styled' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/src/utils/tagged-template-literal' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/hard/indentation' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/hard/invalid-indentation' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/hard/source-maps' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/interpolations/invalid' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/interpolations/valid' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/simple/global' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/simple/helpers' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/simple/imports' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/simple/invalid' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/simple/nesting' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/fixtures/simple/valid' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/hard.test' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/interpolations.test' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/simple.test' {
  declare module.exports: any;
}

declare module 'stylelint-processor-styled-components/test/utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-processor-styled-components/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/coverage/lcov-report/prettify'>;
}
declare module 'stylelint-processor-styled-components/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/coverage/lcov-report/sorter'>;
}
declare module 'stylelint-processor-styled-components/lib/index.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/lib/index'>;
}
declare module 'stylelint-processor-styled-components/lib/utils/general.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/lib/utils/general'>;
}
declare module 'stylelint-processor-styled-components/lib/utils/parse.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/lib/utils/parse'>;
}
declare module 'stylelint-processor-styled-components/lib/utils/styled.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/lib/utils/styled'>;
}
declare module 'stylelint-processor-styled-components/lib/utils/tagged-template-literal.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/lib/utils/tagged-template-literal'>;
}
declare module 'stylelint-processor-styled-components/src/index.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/src/index'>;
}
declare module 'stylelint-processor-styled-components/src/utils/general.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/src/utils/general'>;
}
declare module 'stylelint-processor-styled-components/src/utils/parse.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/src/utils/parse'>;
}
declare module 'stylelint-processor-styled-components/src/utils/styled.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/src/utils/styled'>;
}
declare module 'stylelint-processor-styled-components/src/utils/tagged-template-literal.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/src/utils/tagged-template-literal'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/hard/indentation.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/hard/indentation'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/hard/invalid-indentation.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/hard/invalid-indentation'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/hard/source-maps.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/hard/source-maps'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/interpolations/invalid.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/interpolations/invalid'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/interpolations/valid.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/interpolations/valid'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/simple/global.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/simple/global'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/simple/helpers.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/simple/helpers'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/simple/imports.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/simple/imports'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/simple/invalid.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/simple/invalid'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/simple/nesting.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/simple/nesting'>;
}
declare module 'stylelint-processor-styled-components/test/fixtures/simple/valid.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/fixtures/simple/valid'>;
}
declare module 'stylelint-processor-styled-components/test/hard.test.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/hard.test'>;
}
declare module 'stylelint-processor-styled-components/test/interpolations.test.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/interpolations.test'>;
}
declare module 'stylelint-processor-styled-components/test/simple.test.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/simple.test'>;
}
declare module 'stylelint-processor-styled-components/test/utils.test.js' {
  declare module.exports: $Exports<'stylelint-processor-styled-components/test/utils.test'>;
}
