// flow-typed signature: 181b6c8fff7c35bc5b6a1a9b4f7c53ce
// flow-typed version: <<STUB>>/webpack-merge_v^2.4.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-merge/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/join-arrays-smart' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/join-arrays' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/unique' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/unite-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-merge/lib/index.js' {
  declare module.exports: $Exports<'webpack-merge/lib/index'>;
}
declare module 'webpack-merge/lib/join-arrays-smart.js' {
  declare module.exports: $Exports<'webpack-merge/lib/join-arrays-smart'>;
}
declare module 'webpack-merge/lib/join-arrays.js' {
  declare module.exports: $Exports<'webpack-merge/lib/join-arrays'>;
}
declare module 'webpack-merge/lib/unique.js' {
  declare module.exports: $Exports<'webpack-merge/lib/unique'>;
}
declare module 'webpack-merge/lib/unite-rules.js' {
  declare module.exports: $Exports<'webpack-merge/lib/unite-rules'>;
}
