// @flow
import type {
  SET_SHOW_ONLY_ILLUST_TYPE,
  SET_SHOW_CAPTION_TYPE,
  ADD_TAG_FILTER_TYPE,
  REMOVE_TAG_FILTER_TYPE,
} from './actionTypes.js'

export const SET_SHOW_ONLY_ILLUST: SET_SHOW_ONLY_ILLUST_TYPE =
  'SettingModal/SET_SHOW_ONLY_ILLUST'
export const SET_SHOW_CAPTION: SET_SHOW_CAPTION_TYPE =
  'SettingModal/SET_SHOW_CAPTION'
export const ADD_TAG_FILTER: ADD_TAG_FILTER_TYPE = 'SettingModal/ADD_TAG_FILTER'
export const REMOVE_TAG_FILTER: REMOVE_TAG_FILTER_TYPE =
  'SettingModal/REMOVE_TAG_FILTER'
