// @flow
import type {
  ADD_COLUMN_TYPE,
  ADD_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_USER_ILLUST_TYPE,
  FETCH_USER_ILLUST_SUCCESS_TYPE,
  FETCH_USER_ILLUST_FAILRE_TYPE,
  FETCH_NEXT_USER_ILLUST_TYPE,
  FETCH_NEXT_USER_ILLUST_SUCCESS_TYPE,
  FETCH_NEXT_USER_ILLUST_FAILRE_TYPE,
} from './actionTypes.js'

export const ADD_COLUMN: ADD_COLUMN_TYPE = 'ColumnUserIllust/ADD_COLUMN'
export const ADD_COLUMN_SUCCESS: ADD_COLUMN_SUCCESS_TYPE =
  'ColumnUserIllust/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnUserIllust/SET_NEXT_URL'
export const FETCH_USER_ILLUST: FETCH_USER_ILLUST_TYPE =
  'ColumnUserIllust/FETCH_USER_ILLUST'
export const FETCH_USER_ILLUST_SUCCESS: FETCH_USER_ILLUST_SUCCESS_TYPE =
  'ColumnUserIllust/FETCH_USER_ILLUST_SUCCESS'
export const FETCH_USER_ILLUST_FAILRE: FETCH_USER_ILLUST_FAILRE_TYPE =
  'ColumnUserIllust/FETCH_USER_ILLUST_FAILRE'
export const FETCH_NEXT_USER_ILLUST: FETCH_NEXT_USER_ILLUST_TYPE =
  'ColumnUserIllust/FETCH_NEXT_USER_ILLUST'
export const FETCH_NEXT_USER_ILLUST_SUCCESS: FETCH_NEXT_USER_ILLUST_SUCCESS_TYPE =
  'ColumnUserIllust/FETCH_NEXT_USER_ILLUST_SUCCESS'
export const FETCH_NEXT_USER_ILLUST_FAILRE: FETCH_NEXT_USER_ILLUST_FAILRE_TYPE =
  'ColumnUserIllust/FETCH_NEXT_USER_ILLUST_FAILRE'
