// @flow
import type {
  FETCH_REQUEST_TYPE,
  FETCH_SUCCESS_TYPE,
  FETCH_FAILRE_TYPE,
} from './actionTypes'

export const FETCH_REQUEST: FETCH_REQUEST_TYPE = 'SearchField/FETCH_REQUEST'
export const FETCH_SUCCESS: FETCH_SUCCESS_TYPE = 'SearchField/FETCH_SUCCESS'
export const FETCH_FAILRE: FETCH_FAILRE_TYPE = 'SearchField/FETCH_FAILRE'
