// @flow
import type {
  ADD_COLUMN_SEARCH_ILLUST_TYPE,
  CLOSE_SEARCH_FIELD_TYPE,
} from './actionTypes.js'

export const ADD_COLUMN_SEARCH_ILLUST: ADD_COLUMN_SEARCH_ILLUST_TYPE =
  'ADD_COLUMN_SEARCH_ILLUST'
export const CLOSE_SEARCH_FIELD: CLOSE_SEARCH_FIELD_TYPE = 'CLOSE_SEARCH_FIELD'
