import {
  ADD_COLUMN_TYPE,
  ADD_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  CLERE_TYPE,
  FETCH_TYPE,
  FETCH_SUCCESS_TYPE,
  FETCH_FAILRE_TYPE,
  FETCH_NEXT_TYPE,
  FETCH_NEXT_SUCCESS_TYPE,
  FETCH_NEXT_FAILRE_TYPE,
  START_WATCH_TYPE,
  WATCH_NEW_TYPE,
} from './actionTypes'

export const ADD_COLUMN: ADD_COLUMN_TYPE = 'ColumnRankingR18/ADD_COLUMN'
export const ADD_COLUMN_SUCCESS: ADD_COLUMN_SUCCESS_TYPE =
  'ColumnRankingR18/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnRankingR18/SET_NEXT_URL'
export const CLERE: CLERE_TYPE = 'ColumnRankingR18/CLERE'
export const FETCH: FETCH_TYPE = 'ColumnRankingR18/FETCH'
export const FETCH_SUCCESS: FETCH_SUCCESS_TYPE =
  'ColumnRankingR18/FETCH_SUCCESS'
export const FETCH_FAILRE: FETCH_FAILRE_TYPE = 'ColumnRankingR18/FETCH_FAILRE'
export const FETCH_NEXT: FETCH_NEXT_TYPE = 'ColumnRankingR18/FETCH_NEXT'
export const FETCH_NEXT_SUCCESS: FETCH_NEXT_SUCCESS_TYPE =
  'ColumnRankingR18/FETCH_NEXT_SUCCESS'
export const FETCH_NEXT_FAILRE: FETCH_NEXT_FAILRE_TYPE =
  'ColumnRankingR18/FETCH_NEXT_FAILRE'
export const START_WATCH: START_WATCH_TYPE = 'ColumnRankingR18/START_WATCH'
export const WATCH_NEW: WATCH_NEW_TYPE = 'ColumnRankingR18/WATCH_NEW'
