// @flow
import type {
  ADD_RANKING_R18_COLUMN_TYPE,
  ADD_RANKING_R18_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_RANKING_R18_TYPE,
  FETCH_RANKING_R18_SUCCESS_TYPE,
  FETCH_RANKING_R18_FAILRE_TYPE,
} from './actionTypes.js'

export const ADD_RANKING_R18_COLUMN: ADD_RANKING_R18_COLUMN_TYPE =
  'ColumnRankingR18/ADD_COLUMN'
export const ADD_RANKING_R18_COLUMN_SUCCESS: ADD_RANKING_R18_COLUMN_SUCCESS_TYPE =
  'ColumnRankingR18/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnRankingR18/SET_NEXT_URL'
export const FETCH_RANKING_R18: FETCH_RANKING_R18_TYPE =
  'ColumnRankingR18/FETCH_RANKING_R18'
export const FETCH_RANKING_R18_SUCCESS: FETCH_RANKING_R18_SUCCESS_TYPE =
  'ColumnRankingR18/FETCH_RANKING_R18_SUCCESS'
export const FETCH_RANKING_R18_FAILRE: FETCH_RANKING_R18_FAILRE_TYPE =
  'ColumnRankingR18/FETCH_RANKING_R18_FAILRE'
