import { ADD_HISTORY_TYPE, ADD_COLUMN_HISTORY_TYPE } from './actionTypes'

export const ADD_HISTORY: ADD_HISTORY_TYPE = 'ColumnHistory/ADD_HISTORY'
export const ADD_COLUMN_HISTORY: ADD_COLUMN_HISTORY_TYPE =
  'ColumnHistory/ADD_COLUMN_HISTORY'
