// @flow
export const ADD_COLUMN_BOOKMARK = 'ADD_COLUMN_BOOKMARK'
export const ADD_COLUMN_FOLLOW = 'ADD_COLUMN_FOLLOW'
export const ADD_COLUMN_RANKING = 'ADD_COLUMN_RANKING'
export const ADD_COLUMN_R18_RANKING = 'ADD_COLUMN_R18_RANKING'
export const ADD_COLUMN_SEARCH_ILLUST = 'ADD_COLUMN_SEARCH_ILLUST'
export const ADD_COLUMN_USER_ILLUSTS = 'ADD_COLUMN_USER_ILLUSTS'
