// @flow
export const SET_PARAMS = 'SET_PARAMS';
export const ADD_COLUMN_ILLUSTS = 'ADD_COLUMN_ILLUSTS';
export const NEXT_COLUMN_ILLUSTS = 'NEXT_COLUMN_ILLUSTS';
export const CLOSE_COLUMN = 'CLOSE_COLUMN';
export const SET_COLUMN_MIN_BOOKMARKS = 'SET_COLUMN_MIN_BOOKMARKS';
export const NEXT_COLUMN_PAGE = 'NEXT_COLUMN_PAGE';
export const ADD_COLUMN = 'ADD_COLUMN';
export const CHECK_COLUMN_UPDATE = 'CHECK_COLUMN_UPDATE';
export const REFRESH_ALL_COLUMNS = 'REFRESH_ALL_COLUMNS';
export const FETCH_COLUMN = 'FETCH_COLUMN';
