// @flow
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'

export const START_IMG_LOADING = 'START_IMG_LOADING'
export const FINISH_IMG_LOADED = 'FINISH_IMG_LOADED'

export const SET_CURRENT_ILLUST = 'SET_CURRENT_ILLUST'
