// @flow
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'

export const OPEN_SEARCH_FIELD = 'OPEN_SEARCH_FIELD'
export const CLOSE_SEARCH_FIELD = 'CLOSE_SEARCH_FIELD'
export const TOGGLE_SEARCH_FIELD = 'TOGGLE_SEARCH_FIELD'

export const OPEN_DROPDOWN = 'OPEN_DROPDOWN'
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN'
export const CLOSE_DROPDOWN = 'CLOSE_DROPDOWN'

export const OPEN_IMAGE_VIEW = 'OPEN_IMAGE_VIEW'
export const CLOSE_IMAGE_VIEW = 'CLOSE_IMAGE_VIEW'

export const OPEN_MANGA_PREVIEW = 'OPEN_MANGA_PREVIEW'
export const CLOSE_MANGA_PREVIEW = 'CLOSE_MANGA_PREVIEW'

export const START_IMG_LOADING = 'START_IMG_LOADING'
export const FINISH_IMG_LOADED = 'FINISH_IMG_LOADED'

export const SET_CURRENT_ILLUST = 'SET_CURRENT_ILLUST'
