// @flow
import type {
  ADD_COLUMN_TYPE,
  ADD_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_TYPE,
  FETCH_SUCCESS_TYPE,
  FETCH_FAILRE_TYPE,
  FETCH_NEXT_TYPE,
  FETCH_NEXT_SUCCESS_TYPE,
  FETCH_NEXT_FAILRE_TYPE,
  FETCH_NEW_TYPE,
  FETCH_NEW_SUCCESS_TYPE,
  FETCH_NEW_FAILRE_TYPE,
  SET_MIN_BOOKBOOK_TYPE,
  SET_INTERVAL_TYPE,
  USERS_IN_TYPE,
  SET_USERS_IN_TYPE,
  RESET_IDS_TYPE,
  START_WATCH_TYPE,
  WATCH_NEW_TYPE,
} from './actionTypes'

export const ADD_COLUMN: ADD_COLUMN_TYPE = 'ColumnSearch/ADD_COLUMN'
export const ADD_COLUMN_SUCCESS: ADD_COLUMN_SUCCESS_TYPE =
  'ColumnSearch/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnSearch/SET_NEXT_URL'
export const FETCH: FETCH_TYPE = 'ColumnSearch/FETCH'
export const FETCH_SUCCESS: FETCH_SUCCESS_TYPE = 'ColumnSearch/FETCH_SUCCESS'
export const FETCH_FAILRE: FETCH_FAILRE_TYPE = 'ColumnSearch/FETCH_FAILRE'
export const FETCH_NEXT: FETCH_NEXT_TYPE = 'ColumnSearch/FETCH_NEXT'
export const FETCH_NEXT_SUCCESS: FETCH_NEXT_SUCCESS_TYPE =
  'ColumnSearch/FETCH_NEXT_SUCCESS'
export const FETCH_NEXT_FAILRE: FETCH_NEXT_FAILRE_TYPE =
  'ColumnSearch/FETCH_NEXT_FAILRE'
export const FETCH_NEW: FETCH_NEW_TYPE = 'ColumnSearch/FETCH_USER_NEW_ILLUST'
export const FETCH_NEW_SUCCESS: FETCH_NEW_SUCCESS_TYPE =
  'ColumnSearch/FETCH_NEW_SUCCESS'
export const FETCH_NEW_FAILRE: FETCH_NEW_FAILRE_TYPE =
  'ColumnSearch/FETCH_NEW_FAILRE'
export const SET_MIN_BOOKBOOK: SET_MIN_BOOKBOOK_TYPE =
  'ColumnSearch/SET_MIN_BOOKBOOK'
export const SET_INTERVAL: SET_INTERVAL_TYPE = 'ColumnSearch/SET_INTERVAL'
export const USERS_IN: USERS_IN_TYPE = 'ColumnSearch/USERS_IN'
export const SET_USERS_IN: SET_USERS_IN_TYPE = 'ColumnSearch/SET_USERS_IN'
export const RESET_IDS: RESET_IDS_TYPE = 'ColumnSearch/RESET_IDS'
export const START_WATCH: START_WATCH_TYPE = 'ColumnSearch/START_WATCH'
export const WATCH_NEW: WATCH_NEW_TYPE = 'ColumnSearch/WATCH_NEW'
