// @flow
import type {
  ADD_RANKING_COLUMN_TYPE,
  ADD_RANKING_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_RANKING_TYPE,
  FETCH_RANKING_SUCCESS_TYPE,
  FETCH_RANKING_FAILRE_TYPE,
} from './actionTypes.js'

export const ADD_RANKING_COLUMN: ADD_RANKING_COLUMN_TYPE =
  'ColumnRanking/ADD_COLUMN'
export const ADD_RANKING_COLUMN_SUCCESS: ADD_RANKING_COLUMN_SUCCESS_TYPE =
  'ColumnRanking/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnRanking/SET_NEXT_URL'
export const FETCH_RANKING: FETCH_RANKING_TYPE = 'ColumnRanking/FETCH_RANKING'
export const FETCH_RANKING_SUCCESS: FETCH_RANKING_SUCCESS_TYPE =
  'ColumnRanking/FETCH_RANKING_SUCCESS'
export const FETCH_RANKING_FAILRE: FETCH_RANKING_FAILRE_TYPE =
  'ColumnRanking/FETCH_RANKING_FAILRE'
