// @flow
import type {
  ADD_COLUMN_TYPE,
  ADD_COLUMN_SUCCESS_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_TYPE,
  FETCH_SUCCESS_TYPE,
  FETCH_FAILRE_TYPE,
  FETCH_NEXT_TYPE,
  FETCH_NEXT_SUCCESS_TYPE,
  FETCH_NEXT_FAILRE_TYPE,
} from './actionTypes.js'

export const ADD_COLUMN: ADD_COLUMN_TYPE = 'ColumnRanking/ADD_COLUMN'
export const ADD_COLUMN_SUCCESS: ADD_COLUMN_SUCCESS_TYPE =
  'ColumnRanking/ADD_COLUMN_SUCCESS'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'ColumnRanking/SET_NEXT_URL'
export const FETCH: FETCH_TYPE = 'ColumnRanking/FETCH'
export const FETCH_SUCCESS: FETCH_SUCCESS_TYPE = 'ColumnRanking/FETCH_SUCCESS'
export const FETCH_FAILRE: FETCH_FAILRE_TYPE = 'ColumnRanking/FETCH_FAILRE'
export const FETCH_NEXT: FETCH_NEXT_TYPE = 'ColumnRanking/FETCH_NEXT'
export const FETCH_NEXT_SUCCESS: FETCH_NEXT_SUCCESS_TYPE =
  'ColumnRanking/FETCH_NEXT_SUCCESS'
export const FETCH_NEXT_FAILRE: FETCH_NEXT_FAILRE_TYPE =
  'ColumnRanking/FETCH_NEXT_FAILRE'
