// @flow
import type {
  ADD_BOOKMARK_REQUEST_TYPE,
  ADD_BOOKMARK_SUCCESS_TYPE,
  ADD_BOOKMARK_FAILER_TYPE,
  DELETE_BOOKMARK_REQUEST_TYPE,
  DELETE_BOOKMARK_SUCCESS_TYPE,
  DELETE_BOOKMARK_FAILER_TYPE,
} from './actionTypes'

export const ADD_BOOKMARK_REQUEST: ADD_BOOKMARK_REQUEST_TYPE =
  'BookmarkButton/ADD_BOOKMARK_REQUEST'
export const ADD_BOOKMARK_SUCCESS: ADD_BOOKMARK_SUCCESS_TYPE =
  'BookmarkButton/ADD_BOOKMARK_SUCCESS'
export const ADD_BOOKMARK_FAILER: ADD_BOOKMARK_FAILER_TYPE =
  'BookmarkButton/ADD_BOOKMARK_FAILER'
export const DELETE_BOOKMARK_REQUEST: DELETE_BOOKMARK_REQUEST_TYPE =
  'BookmarkButton/ELETE_BOOKMARK_REQUEST'
export const DELETE_BOOKMARK_SUCCESS: DELETE_BOOKMARK_SUCCESS_TYPE =
  'BookmarkButton/DELETE_BOOKMARK_SUCCESS'
export const DELETE_BOOKMARK_FAILER: DELETE_BOOKMARK_FAILER_TYPE =
  'BookmarkButton/DELETE_BOOKMARK_FAILER'
