// @flow
import type {
  FETCH_ILLUST_TYPE,
  FETCH_ILLUST_SUCCESS_TYPE,
  FETCH_ILLUST_FAILURE_TYPE,
  FETCH_MANGA_TYPE,
  FETCH_MANGA_SUCCESS_TYPE,
  FETCH_MANGA_FAILURE_TYPE,
  ADD_DRAWER_USER_TYPE,
  ADD_DRAWER_PROFILE_TYPE,
  ADD_DRAWER_ILLUST_IDS_TYPE,
  ADD_DRAWER_MANGA_IDS_TYPE,
  SET_NEXT_ILLUST_URL_TYPE,
  SET_NEXT_MANGA_URL_TYPE,
  FETCH_USER_DETAIL_TYPE,
  FETCH_USER_DETAIL_SUCCESS_TYPE,
  FETCH_USER_DETAIL_FAILURE_TYPE,
  NEXT_ILLUST_PAGE_TYPE,
  NEXT_ILLUST_PAGE_SUCCESS_TYPE,
  NEXT_ILLUST_PAGE_FAILURE_TYPE,
  NEXT_MANGA_PAGE_TYPE,
  NEXT_MANGA_PAGE_SUCCESS_TYPE,
  NEXT_MANGA_PAGE_FAILURE_TYPE,
} from './actionTypes.js'

export const FETCH_ILLUST: FETCH_ILLUST_TYPE = 'UserDrawer/FETCH_ILLUST'
export const FETCH_ILLUST_SUCCESS: FETCH_ILLUST_SUCCESS_TYPE =
  'UserDrawer/FETCH_ILLUST_SUCCESS'
export const FETCH_ILLUST_FAILURE: FETCH_ILLUST_FAILURE_TYPE =
  'UserDrawer/FETCH_ILLUST_FAILURE'
export const FETCH_MANGA: FETCH_MANGA_TYPE = 'UserDrawer/FETCH_MANGA'
export const FETCH_MANGA_SUCCESS: FETCH_MANGA_SUCCESS_TYPE =
  'UserDrawer/FETCH_MANGA_SUCCESS'
export const FETCH_MANGA_FAILURE: FETCH_MANGA_FAILURE_TYPE =
  'UserDrawer/FETCH_MANGA_FAILURE'
export const ADD_DRAWER_USER: ADD_DRAWER_USER_TYPE =
  'UserDrawer/ADD_DRAWER_USER'
export const ADD_DRAWER_PROFILE: ADD_DRAWER_PROFILE_TYPE =
  'UserDrawer/ADD_DRAWER_PROFILE'
export const ADD_DRAWER_ILLUST_IDS: ADD_DRAWER_ILLUST_IDS_TYPE =
  'UserDrawer/ADD_DRAWER_ILLUST_IDS'
export const ADD_DRAWER_MANGA_IDS: ADD_DRAWER_MANGA_IDS_TYPE =
  'UserDrawer/ADD_DRAWER_MANGA_IDS'
export const SET_NEXT_ILLUST_URL: SET_NEXT_ILLUST_URL_TYPE =
  'UserDrawer/SET_NEXT_ILLUST_URL'
export const SET_NEXT_MANGA_URL: SET_NEXT_MANGA_URL_TYPE =
  'UserDrawer/SET_NEXT_MANGA_URL'
export const FETCH_USER_DETAIL: FETCH_USER_DETAIL_TYPE =
  'UserDrawer/FETCH_USER_DETAIL'
export const FETCH_USER_DETAIL_SUCCESS: FETCH_USER_DETAIL_SUCCESS_TYPE =
  'UserDrawer/FETCH_USER_DETAIL_SUCCESS'
export const FETCH_USER_DETAIL_FAILURE: FETCH_USER_DETAIL_FAILURE_TYPE =
  'UserDrawer/FETCH_USER_DETAIL_FAILURE'
export const NEXT_ILLUST_PAGE: NEXT_ILLUST_PAGE_TYPE =
  'UserDrawer/NEXT_PAGE_ILLUST'
export const NEXT_ILLUST_PAGE_SUCCESS: NEXT_ILLUST_PAGE_SUCCESS_TYPE =
  'UserDrawer/NEXT_ILLUST_PAGE_SUCCESS'
export const NEXT_ILLUST_PAGE_FAILURE: NEXT_ILLUST_PAGE_FAILURE_TYPE =
  'UserDrawer/NEXT_ILLUST_PAGE_FAILURE'
export const NEXT_MANGA_PAGE: NEXT_MANGA_PAGE_TYPE =
  'UserDrawer/NEXT_PAGE_MANGA_'
export const NEXT_MANGA_PAGE_SUCCESS: NEXT_MANGA_PAGE_SUCCESS_TYPE =
  'UserDrawer/NEXT_MANGA_PAGE_SUCCESS'
export const NEXT_MANGA_PAGE_FAILURE: NEXT_MANGA_PAGE_FAILURE_TYPE =
  'UserDrawer/NEXT_MANGA_PAGE_FAILURE'
