// @flow
import type {
  FETCH_DRAWER_ILLUST_TYPE,
  FETCH_DRAWER_ILLUST_SUCCESS_TYPE,
  FETCH_DRAWER_ILLUST_FAILURE_TYPE,
  ADD_DRAWER_USER_TYPE,
  ADD_DRAWER_ILLUSTS_TYPE,
  ADD_DRAWER_PROFILE_TYPE,
  SET_NEXT_URL_TYPE,
  FETCH_USER_DETAIL_TYPE,
  FETCH_USER_DETAIL_SUCCESS_TYPE,
  FETCH_USER_DETAIL_FAILURE_TYPE,
  NEXT_DRAWER_PAGE_TYPE,
  NEXT_DRAWER_PAGE_SUCCESS_TYPE,
  NEXT_DRAWER_PAGE_FAILURE_TYPE,
} from './actionTypes.js'

export const FETCH_DRAWER_ILLUST: FETCH_DRAWER_ILLUST_TYPE =
  'UserDrawer/FETCH_DRAWER_ILLUST'
export const FETCH_DRAWER_ILLUST_SUCCESS: FETCH_DRAWER_ILLUST_SUCCESS_TYPE =
  'UserDrawer/FETCH_DRAWER_ILLUST_SUCCESS'
export const FETCH_DRAWER_ILLUST_FAILURE: FETCH_DRAWER_ILLUST_FAILURE_TYPE =
  'UserDrawer/FETCH_DRAWER_ILLUST_FAILURE'
export const ADD_DRAWER_USER: ADD_DRAWER_USER_TYPE =
  'UserDrawer/ADD_DRAWER_USER'
export const ADD_DRAWER_ILLUSTS: ADD_DRAWER_ILLUSTS_TYPE =
  'UserDrawer/ADD_DRAWER_ILLUSTS'
export const ADD_DRAWER_PROFILE: ADD_DRAWER_PROFILE_TYPE =
  'UserDrawer/ADD_DRAWER_PROFILE'
export const SET_NEXT_URL: SET_NEXT_URL_TYPE = 'UserDrawer/SET_NEXT_URL'
export const FETCH_USER_DETAIL: FETCH_USER_DETAIL_TYPE =
  'UserDrawer/FETCH_USER_DETAIL'
export const FETCH_USER_DETAIL_SUCCESS: FETCH_USER_DETAIL_SUCCESS_TYPE =
  'UserDrawer/FETCH_USER_DETAIL_SUCCESS'
export const FETCH_USER_DETAIL_FAILURE: FETCH_USER_DETAIL_FAILURE_TYPE =
  'UserDrawer/FETCH_USER_DETAIL_FAILURE'
export const NEXT_DRAWER_PAGE: NEXT_DRAWER_PAGE_TYPE =
  'UserDrawer/NEXT_DRAWER_PAGE'
export const NEXT_DRAWER_PAGE_SUCCESS: NEXT_DRAWER_PAGE_SUCCESS_TYPE =
  'UserDrawer/NEXT_DRAWER_PAGE_SUCCESS'
export const NEXT_DRAWER_PAGE_FAILURE: NEXT_DRAWER_PAGE_FAILURE_TYPE =
  'UserDrawer/NEXT_DRAWER_PAGE_FAILURE'
