import {
  FOLLOW_REQUEST_TYPE,
  FOLLOW_SUCCESS_TYPE,
  FOLLOW_FAILER_TYPE,
  UN_FOLLOW_REQUEST_TYPE,
  UN_FOLLOW_SUCCESS_TYPE,
  UN_FOLLOW_FAILER_TYPE,
} from './actionTypes'

export const FOLLOW_REQUEST: FOLLOW_REQUEST_TYPE = 'FollowButton/FOLLOW_REQUEST'
export const FOLLOW_SUCCESS: FOLLOW_SUCCESS_TYPE = 'FollowButton/FOLLOW_SUCCESS'
export const FOLLOW_FAILER: FOLLOW_FAILER_TYPE = 'FollowButton/FOLLOW_FAILER'
export const UN_FOLLOW_REQUEST: UN_FOLLOW_REQUEST_TYPE =
  'FollowButton/UN_FOLLOW_REQUEST'
export const UN_FOLLOW_SUCCESS: UN_FOLLOW_SUCCESS_TYPE =
  'FollowButton/UN_FOLLOW_SUCCESS'
export const UN_FOLLOW_FAILER: UN_FOLLOW_FAILER_TYPE =
  'FollowButton/UN_FOLLOW_FAILER'
